# Generated by Django 3.0.4 on 2020-03-29 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_list_listitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
